repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-merge-conflict
          - id: check-case-conflict
    - repo: local
      hooks:
          - id: prettier
            name: Format JS/TS code with prettier
            entry: npx prettier --check
            language: system
            types: [file]
            files: '\.(js|jsx|ts|tsx)$'
            stages: ["pre-push"]
